name: deploy

on:
  push:
    tags:
    - '*'

jobs:
  Deploy:
    name: Deploy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Docs
        run: ./CI/publish-docs.sh

      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
