name: tests

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:
  Tests:
    name: Tests
    runs-on: macos-latest
    env:
      PROJECT: VirgilCrypto.xcodeproj
    strategy:
      matrix:
        include:
          - destination: "platform=iOS Simulator,name=iPhone 16"
            prefix: "iOS"
            test: "1"
          - destination: "arch=x86_64"
            prefix: "macOS"
            test: "1"
          - destination: "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)"
            prefix: "tvOS"
            test: "1"
          - destination: "platform=watchOS Simulator,name=Apple Watch Series 10 (46mm)"
            prefix: "watchOS"
            test: "0"
          - destination: "generic/platform=iOS"
            prefix: "iOS"
            test: "0"
          - destination: "generic/platform=tvOS"
            prefix: "tvOS"
            test: "0"
          - destination: "generic/platform=watchOS"
            prefix: "watchOS"
            test: "0"
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.prefix }} Tests
        uses: nick-fields/retry@v2
        with:
          max_attempts: 20
          timeout_minutes: 10
          retry_on: error
          command: |
            set -o pipefail
            SCHEME="VirgilCrypto ${{ matrix.prefix }}"

            if [ "${{ matrix.test }}" == "1" ]; then
                # Build Framework
                xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -destination "${{ matrix.destination }}" -configuration Debug clean test | xcpretty;
            else
                xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -destination "${{ matrix.destination }}" -configuration Release clean build | xcpretty;
            fi
  SPM:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install coreutils # install 'timeout' utility
      - run: swift --version
      - run: timeout 15m bash -c 'until swift build; do rm -fr .build && sleep 10; done' # fix for Swift Package Manager when it fails to download binary targets
      - run: swift test
